site_name: My Docs
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
nav:
- Home: index.md
- Journeys: 
  - Login: Login.md
theme:
  logo: assets/spine.jpg
  name: material
